[package]
name = "sqlited-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
r2d2 = "0.8"
r2d2_sqlite = "0.27"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
sqlformat = "0.3"